FROM node:25.2.1-alpine AS stage

WORKDIR /backend

COPY package*.json ./

RUN npm ci

COPY . .

RUN mkdir -p /backend/data

FROM dhi.io/node:25-alpine3.22 AS runtime

WORKDIR /backend

COPY --from=stage /backend/node_modules ./node_modules

COPY --from=stage /backend/src ./src

COPY --from=stage /backend/db.js ./

COPY --from=stage --chown=1000:1000 /backend/data /app/data

COPY --from=stage /backend/adapters ./adapters

COPY --from=stage /backend/config.js ./

COPY --from=stage /backend/package*.json ./


EXPOSE 4000

# HEALTHCHECK --interval=5m --timeout=3s \
#   CMD curl -f http://localhost:4000/health || exit 1

CMD ["node", "src/index.js"]